apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask
spec:
  selector:
    matchLabels:
      app: simple-flask
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-flask
    spec:
      containers:
      - name: simple-flask-pod
        image: iad.ocir.io/idvtakawrwao/simple-flask-app:arm
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-flask-service
spec:
  selector:
    app: simple-flask
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
